#!/usr/bin/env bash
# Superstitious numbers

count=1
while [ $count -le 20 ]
do
	echo $count
	case $count in
		4)
			echo "bad luck from china"
			;;
		9)
			echo "bad luck from japan"
			;;
		17)
			echo "bad luck from italy"
			;;
	esac
	((count++))
done
